//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Com.BraveLocation.BedsideClock {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Com.BraveLocation.BedsideClock.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutSettingsLinkText {
            get {
                return ResourceManager.GetString("AboutSettingsLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bedside Clock is brought to you by Brave Location.
        ///
        ///The weather data is from Yahoo Weather!, and the icons used are thanks to Gavin Elliott from happie.st.
        /// </summary>
        public static string AboutText1 {
            get {
                return ResourceManager.GetString("AboutText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brave Location Website.
        /// </summary>
        public static string BraveLocationSiteLinkText {
            get {
                return ResourceManager.GetString("BraveLocationSiteLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to brighter.
        /// </summary>
        public static string BrighterButtonText {
            get {
                return ResourceManager.GetString("BrighterButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hide.
        /// </summary>
        public static string CloseButtonText {
            get {
                return ResourceManager.GetString("CloseButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimmed.
        /// </summary>
        public static string DimmedSettingsText {
            get {
                return ResourceManager.GetString("DimmedSettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dimmer.
        /// </summary>
        public static string DimmerButtonText {
            get {
                return ResourceManager.GetString("DimmerButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gavin Elliott&apos;s Weather Icons.
        /// </summary>
        public static string ElliottLinkText {
            get {
                return ResourceManager.GetString("ElliottLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Brave Location Team.
        /// </summary>
        public static string FeedbackLinkText {
            get {
                return ResourceManager.GetString("FeedbackLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching ....
        /// </summary>
        public static string InitialLocationText {
            get {
                return ResourceManager.GetString("InitialLocationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to location.
        /// </summary>
        public static string LocationButtonText {
            get {
                return ResourceManager.GetString("LocationButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location not found.
        /// </summary>
        public static string LocationNotFoundText {
            get {
                return ResourceManager.GetString("LocationNotFoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location service disabled.
        /// </summary>
        public static string LocationServiceDisabledText {
            get {
                return ResourceManager.GetString("LocationServiceDisabledText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Location.
        /// </summary>
        public static string LocationSettingsText {
            get {
                return ResourceManager.GetString("LocationSettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Phase of Moon.
        /// </summary>
        public static string PhaseOfMoonSettingsText {
            get {
                return ResourceManager.GetString("PhaseOfMoonSettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charging?.
        /// </summary>
        public static string PowerOnCheckText {
            get {
                return ResourceManager.GetString("PowerOnCheckText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        public static string PrivacySettingsLinkText {
            get {
                return ResourceManager.GetString("PrivacySettingsLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bedside Clock doesn&apos;t use your location data for anything other than displaying the location on the screen when requested.
        ///
        ///The application uses Yahoo! PlaceFinder to try to turn the user&apos;s location into a place name. The privacy policy of Yahoo! can be found at Yahoo!&apos;s Privacy Page.
        ///
        ///This privacy policy was not written by a lawyer, but simply by the developers of the application, so if you have any questions or issues, please don&apos;t heistate to contact us.
        ///
        ///The Brave Location Team.
        /// </summary>
        public static string PrivacyText1 {
            get {
                return ResourceManager.GetString("PrivacyText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string SettingsOKButtonText {
            get {
                return ResourceManager.GetString("SettingsOKButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsTitleText {
            get {
                return ResourceManager.GetString("SettingsTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Yahoo! Weather.
        /// </summary>
        public static string WeatherSettingsText {
            get {
                return ResourceManager.GetString("WeatherSettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yahoo! Privacy Website.
        /// </summary>
        public static string YahooPrivacySiteLinkText {
            get {
                return ResourceManager.GetString("YahooPrivacySiteLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yahoo! Weather Website.
        /// </summary>
        public static string YahooWeatherLinkText {
            get {
                return ResourceManager.GetString("YahooWeatherLinkText", resourceCulture);
            }
        }
    }
}
